// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softeq.NetKit.Integrations.EventLog;

namespace Softeq.NetKit.Integrations.EventLog.Migrations.HoopIntegrationEventLog
{
    [DbContext(typeof(HoopIntegrationEventLogContext))]
    [Migration("20260601145915_AddHoopIntegrationEventLogs")]
    partial class AddHoopIntegrationEventLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Softeq.NetKit.Integrations.EventLog.IntegrationEventLog", b =>
                {
                    b.Property<Guid>("EventId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<int>("EventState");

                    b.Property<string>("EventTypeName")
                        .IsRequired();

                    b.Property<string>("SessionId");

                    b.Property<int>("TimesSent");

                    b.Property<DateTimeOffset?>("Updated");

                    b.HasKey("EventId");

                    b.HasIndex("Created");

                    b.HasIndex("EventState");

                    b.HasIndex("SessionId");

                    b.ToTable("HoopIntegrationEventLogs","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
